language: python
python:
  - "3.10"
  - "nightly"  # nightly build

# command to install dependencies
install:
  - pip install pipenv
  - pipenv install --dev

script:
  - pytest

after_success:
  - codecov
