language: python
matrix:
  include:
    - python: 3.6
    - python: 3.7
    - python: 3.8
    - python: "3.8-dev"
    dist: xenial
    sudo: true

install:
  - pip install pipenv
  - pipenv install

script:
  - pytest
